# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0003_auto_20180603_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
