# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0004_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='avatar/'),
        ),
    ]
