# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0005_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
